version: "3.9"

services:
  web:
    build:
      context: backend
      target: development
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: trade
      POSTGRES_PASSWORD: vegetation
      POSTGRES_DB: db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/


volumes:
  postgres_data: